export const cities =[
    "New York, United States",
    "Los Angeles, United States",
    "Chicago, United States",
    "Mexico City, Mexico",
    "Toronto, Canada",
    "Vancouver, Canada",
    "London, United Kingdom",
    "Paris, France",
    "Berlin, Germany",
    "Madrid, Spain",
    "Rome, Italy",
    "Amsterdam, Netherlands",
    "Brussels, Belgium",
    "Moscow, Russia",
    "Istanbul, Turkey",
    "Cairo, Egypt",
    "Lagos, Nigeria",
    "Johannesburg, South Africa",
    "Nairobi, Kenya",
    "Cape Town, South Africa",
    "Dubai, United Arab Emirates",
    "Mumbai, India",
    "Delhi, India",
    "Beijing, China",
    "Shanghai, China",
    "Tokyo, Japan",
    "Seoul, South Korea",
    "Bangkok, Thailand",
    "Singapore, Singapore",
    "Kuala Lumpur, Malaysia",
    "Jakarta, Indonesia",
    "Sydney, Australia",
    "Melbourne, Australia",
    "Auckland, New Zealand",
    "Buenos Aires, Argentina",
    "São Paulo, Brazil",
    "Santiago, Chile"
]
